### ISSUE TITLE
Bug?: Guille­mets are not recognised as quotation marks 

### ISSUE THREAD

**Issue by rrmn** [StractOrg/stract#126]
I’m guessing you use `"…"` to enable the search for fixed terms, which is great.

There’s a funny side effect when you use non-English style quotation marks, where they are recognised as part of the search term(s). (E.g. „…“, «…», …)

Still not sure whether a bug or a feature. :-)

<img src="https://github.com/StractOrg/stract/assets/14080347/ab0dbc7e-2c4e-4bb6-aab3-27f87ee4b141" width="200" />
<img src="https://github.com/StractOrg/stract/assets/14080347/2e0101d5-270c-4f00-9649-85047c3e07d4" width="200" />
<img src="https://github.com/StractOrg/stract/assets/14080347/52a26760-78e0-4a87-9c21-5dee44c22ee8" width="200" />

**Comment by mikkeldenker** [comment]
Oh yea, that's a good point. I don't even know what the correct approach should be here. Google, bing and mojeek all seem to perform a phrase search as with english quotes, so I guess this is what most users would expect (and therefore probably what we should also do).

It would be interesting to hear if anyone thinks the quotes should be interpreted the way they are now, and if so why

**Comment by rrmn** [comment]
@mikkeldenker 

### Google's behaviour

 * "..." - fixed term
 * all other special characters get scrubbed

<img width="1032" alt="Screenshot 2024-02-19 at 13 56 55" src="https://github.com/StractOrg/stract/assets/14080347/83f0781a-c2ba-4887-9488-b38484aeca12">


<img width="957" alt="Screenshot 2024-02-19 at 13 57 07" src="https://github.com/StractOrg/stract/assets/14080347/5aeefa5d-2900-4247-9de2-b104be038e30">
