### ISSUE TITLE
[QUESTION] Can Hearchco scrape you?

### ISSUE THREAD

**Issue by aleksasiriski** [StractOrg/stract#130]
Hello, this project looks interesting. As a fellow open source developer I wanted to ask for permission to add your main instance ([stract.com](https://stract.com/)) to [Hearchco](https://github.com/hearchco) meta-search engine. If it is fine by you for us to scrape it, if not I won't be adding it to respect your contributions to the open source community.

**Comment by mikkeldenker** [comment]
Hi! Yea that's totally fine. Thanks a lot for asking beforehand and best of luck with the project!
