### ISSUE TITLE
I don't know how to add your search engine to Firefox

### ISSUE THREAD

**Issue by aaroncommand** [StractOrg/stract#131]
I tried it, I think it's great and I like the unique results it's producing, but the chance I will continue to use it if it's not one of the search engines registered in my browser is exactly zero. I would love it if you made that possible or explained how we can do it, so that we can actually use this cool search engine instead of just seeing it once and forgetting it forever.

**Comment by thiswillbeyourgithub** [comment]
Same here. I was stunned by the quality and I must say that the ability to vote on results quality seems incredible so I'd like to switch from ddg for a while

**Comment by aaroncommand** [comment]
That worked, thanks! While I understand that it's a work in progress I'm continually impressed with the results Stract is delivering, it feels like I'm searching the Internet again instead of a small cabal of Google's most lucrative partners!

**Comment by thiswillbeyourgithub** [comment]
I second this feeling.

Is there an RSS or blog somewhere to keep track of this project? It's indeed too early to use for me but I'd love to see details behind the progress.

**Comment by mikkeldenker** [comment]
I don't know what to say. It has taken a lot of dedication to get to this point, so reading these comments is simply incredible. Thank you so much!

There is no blog yet unfortunately. I am finishing my masters this month (hand-in in 4 days 🤞) and will go full-time on Stract afterwards, so hopefully I will get some more time to write about it then

**Comment by Vinfall** [comment]
> We should probably have a document that outlines this process for all the major browsers.

[Whoogle-search](https://github.com/benbusby/whoogle-search?tab=readme-ov-file#set-whoogle-as-your-primary-search-engine) has instructions on setting whoogle as primary search engine on some browsers, maybe you wannt check it as a reference.

> Is there an RSS or blog somewhere to keep track of this project?

GitHub has Atom feeds for commits (i.e. https://github.com/StractOrg/stract/commits/main.atom) but I think that would be too much traffic and overwhelming if you are not into development _per se_. Maybe the dev can setup a kanban-like roadmap on your [GitHub project](https://github.com/StractOrg/stract/projects) or simply a todo list or blog whatever.

**Comment by edsu** [comment]
> There is no blog yet unfortunately. I am finishing my masters this month (hand-in in 4 days 🤞) and will go full-time on Stract afterwards, so hopefully I will get some more time to write about it then

Good luck! Is your masters thesis about stract? If so it would be awesome if you could share it.

**Comment by mikkeldenker** [comment]
Thank you!
It's actually about computational complexity of evolutionary algorithms, so something else entirely. My bachelor's project was about information retrieval, but it was really more an opportunity for me to learn a lot about the field.
