### ISSUE TITLE
Display issue with non-Unicode encoded results

### ISSUE THREAD

**Issue by nclm** [StractOrg/stract#137]
Noticed that the search preview of pages extract that are not Unicode (at least one that is in windows-1252) doesn’t display right: 

<img width="729" alt="Screenshot 2024-02-09 at 10 43 50" src="https://github.com/StractOrg/stract/assets/923008/6314ed8b-5822-413c-a702-90c5442e98e1">

There might be away to detect the page encoding and get the preview right?

**Comment by mikkeldenker** [comment]
Thanks for the report! It was indeed a mistake in the way we decoded non-utf8 encoded strings. It should be fixed now, but it won't be visible in production until we rebuild the index.
