### ISSUE TITLE
Keyboard shortcuts for navigating

### ISSUE THREAD

**Issue by Hasnabruzzn** [StractOrg/stract#146]
Like 'j' for going to the next search result, 'm' for going to the previous search result, 'h' back to the search field.

**Comment by lamemakes** [comment]
@mikkeldenker Did you have any ideal implementation in mind for this? I was going to use [this](https://duckduckgo.com/duckduckgo-help-pages/features/keyboard-shortcuts/) as my guidepost but wasn't sure if you had anything else in mind before I got started.

**Comment by mikkeldenker** [comment]
> @mikkeldenker Did you have any ideal implementation in mind for this? I was going to use [this](https://duckduckgo.com/duckduckgo-help-pages/features/keyboard-shortcuts/) as my guidepost but wasn't sure if you had anything else in mind before I got started.

That would be perfect I think

**Comment by Hasnabruzzn** [comment]
> @mikkeldenker Did you have any ideal implementation in mind for this? I was going to use [this](https://duckduckgo.com/duckduckgo-help-pages/features/keyboard-shortcuts/) as my guidepost but wasn't sure if you had anything else in mind before I got started.

yep - perfect :-)
