### ISSUE TITLE
stract.com user agent info is not easily discoverable

### ISSUE THREAD

**Issue by ansuz** [StractOrg/stract#158]
Hi!

I heard about your project from [the recen 404media article](https://www.404media.co/this-guy-is-building-an-open-source-search-engine-in-real-time/) and wanted to look into it. Sorry if this isn't the right place to bring this up since it concerns your crawler rather than the software itself.

Most of my websites have a restrictive robots.txt file, and I was considering adding an exemption for your crawler, but I wasn't sure what user-agent to use. I checked [your about page](https://stract.com/about) and some other resources, but didn't find the info anywhere.

Eventually I just did a `grep -i stract.com` on some of my server logs and found a reference to [your webmasters page](https://stract.com/webmasters). Perhaps this page could be more conspicuous in the stract.com web interface?

**Comment by mikkeldenker** [comment]
Thank you for the exemption, that's very nice!

I kinda want to keep the about page as concise as possible, but I've added some links to the top of the readme here on github and to the top of [docs/src/crawler.md](https://github.com/StractOrg/stract/blob/main/docs/src/crawler.md). This will hopefully make it easier to find.
