### ISSUE TITLE
Open Results in New Tab

### ISSUE THREAD

**Issue by Ekpyrotika** [StractOrg/stract#174]
It's a pretty simple request, but it would enhance the user experience to have the option to keep the search results window open and have the links open in new tabs. I love this project so far, though.

**Comment by lamemakes** [comment]
@mikkeldenker were you imagining this as a global preference of a per-result thing?

**Comment by mikkeldenker** [comment]
I think it should be added as a global preference kinda like 'mark-pages-with-ads'. It would be awesome if you wanted to take a go at it.
