### ISSUE TITLE
Support '%' as modulo operator in calculator

### ISSUE THREAD

**Issue by Ashvith10** [StractOrg/stract#190]
When I try calculating `100 % 12`, I get `13` as the answer.

![Screen Shot 2024-04-05 at 21 15 46](https://github.com/StractOrg/stract/assets/113123021/59c9bbaf-c982-4fef-82e2-b160df3a2208)

**Comment by oeb25** [comment]
I did not look into the code, but it seems as if `x%y` is interpreted as `(x/100)+y` and not as modulo. For modulo one would need `x mod y`.

Note that we are using [fend](https://github.com/printfn/fend) for evaluating everything in the calculator.

**Comment by mikkeldenker** [comment]
Yea it seems that fend always treats `%` as a unit. They have an open issue to also support it as a module operator, but it seems that it might not be trivial to implement in their parser (https://github.com/printfn/fend/issues/265).

I kinda want to label this as a bug as I agree this is not what the user expects. I don't know exactly how we should fix it though. I think we could either (in order of ascending difficulty and flexibility):
1. **Hot fix:** replace all `([\d]+) *% *([\d]+)` with `$1 mod $2`.
2. It seems that the maintainer of fend wants this as well, so we might be able to fix it in their parser and upstream it.
3. Write our own calculator.

**Comment by printfn** [comment]
Hello, fend maintainer here! I've implemented a fix for this in v1.4.8.

**Comment by mikkeldenker** [comment]
Awesome! Thanks for the heads up
