### ISSUE TITLE
adding to browser - make instructions easier to find

### ISSUE THREAD

**Issue by BryanQuigley** [StractOrg/stract#191]
Not obvious to me from home page how to get to doc about.  For ease of growth, having instructions on the hope page would be helpful.

It's also not on https://docs.stract.com ?
I do see it was merged https://github.com/StractOrg/stract/pull/135

**Comment by mikkeldenker** [comment]
I apparently forgot to add the file to the navbar in that pr and it therefore didn't show up on https://docs.stract.com 🤦 
This should be fixed now. Thanks for pointing it out!

I kinda want to keep the home page as clean as possible, especially considering that I wouldn't say stract is ready yet to be used as a default search engine, but we will get there
