### ISSUE TITLE
UTF-8 bug in `position_to_byte_offset`

### ISSUE THREAD

**Issue by oeb25** [StractOrg/stract#213]
With non-byte-sized `char`s this decrements the columnar value by the wrong amount.

https://github.com/StractOrg/stract/blob/76d7323524ac1b16eecd40200687f5fb43f442f4/crates/optics-lsp/src/lib.rs#L331

It should instead use

```rust
columns -= c.len_utf8() as u32
```

I noticed this with a round-trip proptest in another project, and remembered there was a similar function somewhere in Stract. I just spotted this one through a basic search, as I quickly wanted to highlight the issue and go back to work, but there might be more. I will look a bit more later!

It might be a good idea to add something similar as the following to Stract where applicable.

```rust
#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        #[test]
        fn round_trip(src in ".*", byte_offset in 0..10_000usize) {
            let pos = Position::from_byte_offset(&src, byte_offset);
            if let Some(b) = pos.to_byte_offset(&src) {
                assert_eq!(byte_offset, b);
            } else if src.is_char_boundary(byte_offset) {
                assert!(byte_offset >= src.len());
            }
        }
    }
}
```

**Comment by mikkeldenker** [comment]
Thanks! I've implented your fix in aabd774e3404c37321fa5e70d5a100417210fa48 and also had a look through the code to add similar proptests to some other places where we index into string slices as well, so this should hopefully be fixed now.
