### ISSUE TITLE
Unclear Manage Optics UI?

### ISSUE THREAD

**Issue by nikostr** [StractOrg/stract#217]
Thank you for this project! It took me a long time to figure out the Manage Optics UI - in particular I did not understand that the eye symbol corresponded to whether to show the optic in the list of available optics in the search, as opposed to e.g. combining multiple optics that apply globally. Would it make sense to clarify this in the UI somewhere?

**Comment by mikkeldenker** [comment]
Thanks for the feedback and the kind words! I've added a tooltip that is shown when one hovers over the eye icon to hopefully make it a bit more clear.

![Screenshot 2024-09-02 at 09 41 22](https://github.com/user-attachments/assets/28586b7b-1661-4a63-ba0b-6e11a7078308)
