### ISSUE TITLE
Add a frontend lockfile

### ISSUE THREAD

**Issue by vesdev** [StractOrg/stract#222]
I would like to package stract as a nix flake for hosting it on my NixOS machine. But the frontend does not contain a lockfile, which is typically useful to prefetch the dependencies in nix with buildNpmPackage etc.

**Comment by mikkeldenker** [comment]
Should be fixed now https://github.com/StractOrg/stract/commit/21d28ea86d9ff19ccb4c25b1bdde67e5ec302d79
