### ISSUE TITLE
Internal Error for all searches

### ISSUE THREAD

**Issue by Paculino** [StractOrg/stract#223]
I realize this is almost certainly a known problem, but I cannot seem to find any information about it. Regardless of browser, I consistently get an internal error or a never-loaded-page when I attempt to search using stract lately. Is there anywhere to read news related to the project, or is that just here?

**Comment by mikkeldenker** [comment]
Thanks for the heads up! It was a configuration error in nginx that caused some issues with https requests sent from the sveltekit server to the backend. It should hopefully be fixed now
