### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by psm227** [StractOrg/stract#81]
Why, when I search for "Stract", none of the results include trystract, or even have stract in the title?

**Comment by mikkeldenker** [comment]
The search index is still very small at the moment but this is something we are working very hard on improving. The current index consist only of approximately 20 million urls while we aim to get 400 million as soon as possible. The index should of course be even larger than this long-term.
Trystract.com is one of the pages that wasn't visited in the last crawl and is therefore not present in the search index yet. 

I actually started another crawl a week ago and saw that the crawler visited trystract.com. Unfortunately the crawl coordinator crashed and it's therefore still the old index that's live on the page, but I suspect trystract.com will get visited during the next crawl.

I'll close this issue as there are no actions to take, but feel free to add a comment here if you have more questions.

**Comment by allywilson** [comment]
I have just started using stract, but I do find the results a bit off.

Search for Microsoft, Apple, IBM, etc. and you would expect their website to be in the results, but none of them are. Which is a bit weird, as I would expect that to be the first result. For those companies, sure, I could just guess, but for others, it might not be so simple (e.g. searching for Brilliant to find the website for Brilliant Labs).
