### ISSUE TITLE
Missing URL encoding for WolframAlpha bang

### ISSUE THREAD

**Issue by oeb25** [StractOrg/stract#82]
The bang [`!wa 1 + 5 + 102`](https://trystract.com/search?q=%21wa+1+%2B+5+%2B+102) redirects to [WolframAlpha correctly](https://www.wolframalpha.com/input?i=1+++5+++102), but the expression does not seem to be encoded correctly, since the input query on WA is `1   5   102` missing the `+`'s.

The given URL query is [`?i=1+++5+++102`](https://www.wolframalpha.com/input?i=1+++5+++102), while the expected is [`?i=1+%2B+5+%2B+102`](https://www.wolframalpha.com/input?i=1+%2B+5+%2B+102).

**Comment by mikkeldenker** [comment]
Thanks for the thorough bug report. I knew exactly where to look because of it.
You were completely right: the queries did not get properly url encoded when sent to the matching bang services. This should now have been fixed in #83
